# Generated by Django 5.2.3 on 2025-06-28 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0003_rename_extention_fileupload_extension_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Folder',
            new_name='CreateFolder',
        ),
    ]
