# Generated by Django 5.2.3 on 2025-06-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0005_alter_fileupload_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to='files'),
        ),
    ]
